worker_processes 2; # If the server has 2 CPU cores

events {
    #...
    worker_connections 1024;
    multi_accept on; 
    use epoll;  
}

http {
    server {
      reset_timedout_connection on;

      client_max_body_size 10M;
      index index.php;
      root /usr/share/nginx/html/public;
      include /etc/nginx/mime.types;



      location ~ \.php$ {
                    add_header Access-Control-Allow-Origin '*';
                    root /usr/share/nginx/html/public;
                    fastcgi_split_path_info ^(.+\.php)(/.+)$; 
                    fastcgi_pass php-fpm:9000;
                    fastcgi_index index.php;
                    fastcgi_buffers 16 16k;
                    fastcgi_buffer_size 32k;
                    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                    include fastcgi_params;
      }

      # Force all /api/* requests through Symfony (handles .json, etc.)
      location /api/ {
            add_header Access-Control-Allow-Origin '*';
            root /usr/share/nginx/html/public;
            try_files $uri /index.php$is_args$args;
      }

        location / {
             add_header Access-Control-Allow-Origin '*';
              index index.html index.htm index.php ;
              try_files $uri $uri/ /index.php$is_args$args;
        }


    } 
}